language: python
python:
  - "3.6"

install:
  - pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install numpy
  - pip install pytest pytest-cov
  - pip install -e .

script:
  - EPHYS_NLM_DEVICE=cpu pytest --cov=ephys_nlm
after_success:
  - bash <(curl -s https://codecov.io/bash) -F travis
