language: python
python:
  - "3.6"
# node_js:
#  - "10"

install:
  - pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install pytest pytest-cov
  - pip install pylint
  # - pip install matplotlib # Only needed for pyright
  # - npm install -g pyright
  - pip install -e .

script:
  # - pyright ephys_nlm
  - pylint ephys_nlm
  - EPHYS_NLM_DEVICE=cpu pytest --cov ephys_nlm --cov-report=xml:cov.xml -s
after_success:
  - bash <(curl -s https://codecov.io/bash) -F travis
